// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH8dhuGmlvAjUd_J6lKxMdr-ZIjtvSXyg',
    appId: '1:662259367528:web:fad2d91bbcb0fc594d05dd',
    messagingSenderId: '662259367528',
    projectId: 'formative-assignment-bba78',
    authDomain: 'formative-assignment-bba78.firebaseapp.com',
    storageBucket: 'formative-assignment-bba78.firebasestorage.app',
    measurementId: 'G-7922GKFD24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq9p0c_aZpIDMHtMbMLXdYiQoErHrU7Dg',
    appId: '1:662259367528:android:b348914b4c29929b4d05dd',
    messagingSenderId: '662259367528',
    projectId: 'formative-assignment-bba78',
    storageBucket: 'formative-assignment-bba78.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8foOoC8ToHDLV7ajqrlT9mEPur0zckXU',
    appId: '1:662259367528:ios:ba6048720212713f4d05dd',
    messagingSenderId: '662259367528',
    projectId: 'formative-assignment-bba78',
    storageBucket: 'formative-assignment-bba78.firebasestorage.app',
    iosBundleId: 'com.example.formativeAssignment',
  );
}
